#!/bin/sh
set -eu

## Script will be run as chrony user (unless enable_sysclk runs as root)

DEFAULT_NTP="0.pool.ntp.org,1.pool.ntp.org,2.pool.ntp.org,3.pool.ntp.org"
CHRONY_CONF_FILE="/etc/chrony/chrony.conf"

CURRENT_USER="$(id -u)"
CURRENT_GROUP="$(id -g)"
CURRENT_USERGROUP="$CURRENT_USER:$CURRENT_GROUP"
CHRONY_USERGROUP="$(id -u chrony):$(id -g chrony)"

echo "
-------------------------------------
Container Information
-------------------------------------
OS: $(. /etc/os-release; echo "${PRETTY_NAME}")
Docker user: $(whoami)
Docker uid: $CURRENT_USER
Docker gid: $CURRENT_GROUP
"

if [ "$CURRENT_USERGROUP" != "$CHRONY_USERGROUP" ]; then
 echo "[WARNING] Container running under a different user than recommended!"
 echo ""
fi

if [ ! -w "/etc/chrony" ] || [ ! -w "/run/chrony" ] || [ ! -w "/var/lib/chrony" ]; then
 echo "
It seems that the necessary folders are not writable by the container user ($CURRENT_USERGROUP).
As this container is running as non-root, it cannot fix the permissions itself.

Please remove the volumes or update them to be writable by $CURRENT_USERGROUP.
Or run the container with 'user: \"0:0\"' so it will run as root so it can fix itself.

If using tmpfs update the config to:
tmpfs:
 - /etc/chrony:rw,mode=1750,uid=$CURRENT_USER,gid=$CURRENT_GROUP
 - /run/chrony:rw,mode=1750,uid=$CURRENT_USER,gid=$CURRENT_GROUP
 - /var/lib/chrony:rw,mode=1750,uid=$CURRENT_USER,gid=$CURRENT_GROUP
"
 exit 1
fi

if [ -d /run/chrony ]; then
 chown -R chrony:chrony /run/chrony 2>/dev/null || true
 chmod o-rx /run/chrony 2>/dev/null || true
 rm -f /var/run/chrony/chronyd.pid
fi

if [ -d /var/lib/chrony ]; then
 chown -R chrony:chrony /var/lib/chrony 2>/dev/null || true
fi

{
 echo "# https://github.com/henryhst/hassio-addons/tree/main/chronyd"
 echo
 echo "# chrony.conf file generated by startup script"
 echo "# located at $0"
 echo
 echo "# time servers provided by NTP_SERVERS environment variables."
} > ${CHRONY_CONF_FILE}

if [ -z "${NTP_SERVERS:-}" ]; then
 NTP_SERVERS="${DEFAULT_NTP}"
fi

if [ -z "${LOG_LEVEL:-}" ]; then
 LOG_LEVEL=0
else
 if expr "${LOG_LEVEL}" : "[^0123]" > /dev/null; then
 LOG_LEVEL=0
 fi
fi

IFS=","
for N in $NTP_SERVERS; do
 N_CLEANED=$(printf "%s" "$N" | tr -d '"')

 if echo "${N_CLEANED}" | grep -q '^127\.'; then
 echo "server ${N_CLEANED}" >> ${CHRONY_CONF_FILE}
 echo "local stratum 10" >> ${CHRONY_CONF_FILE}
 else
 if [ "${ENABLE_NTS:-false}" = true ]; then
 echo "server ${N_CLEANED} iburst nts" >> ${CHRONY_CONF_FILE}
 else
 echo "server ${N_CLEANED} iburst" >> ${CHRONY_CONF_FILE}
 fi
 fi
done

if [ -e /dev/ptp0 ]; then
 echo "refclock PHC /dev/ptp0 poll 3 dpoll -2 stratum 2" >> ${CHRONY_CONF_FILE}
fi

{
 echo
 echo "driftfile /var/lib/chrony/chrony.drift"
 echo "makestep 0.1 3"
 if [ -n "${NTP_DIRECTIVES:-}" ]; then
 echo -e "${NTP_DIRECTIVES}"
 fi
 if [ "${NOCLIENTLOG:-false}" = true ]; then
 echo "noclientlog"
 fi
 echo
 echo "allow all"
} >> ${CHRONY_CONF_FILE}

SYSCLK="-x"
if [ "${ENABLE_SYSCLK:-false}" = true ]; then
 SYSCLK=""
fi

exec /usr/sbin/chronyd -U -u chrony -d ${SYSCLK} -L ${LOG_LEVEL}
