---
name: Corosync QNetd
version: 1.0.3
slug: corosyncd
description: >-
  Corosync QNetd (Quorum Network Daemon) provides an external vote for cluster
  quorum calculations. Essential for 2-node Proxmox VE clusters and preventing
  split-brain scenarios.
url: https://github.com/henryhst/hassio-addons/tree/main/corosyncd
image: ghcr.io/henryhst/hassio-addons/corosyncd
startup: system
arch:
  - aarch64
  - amd64
init: false
hassio_api: true
hassio_role: manager
homeassistant_api: false
panel_icon: mdi:server-network
ports:
  5403/tcp: 5403
ports_description:
  5403/tcp: Corosync QNetd Quorum Device
options:
  log_level: info
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
